### ISSUE TITLE
希望支持使用系统内已设定的 http(s)_proxy 、HTTP(S)_PROXY

### ISSUE THREAD

**Issue by xxxxuanran** [Last-Order/kkr#10]
已经在系统内设置了 http(s)_proxy 、HTTP(S)_PROXY ，且测试可用 curl 访问 被屏蔽的网站，程序依旧报 403 错误。
curl 相关测试如下
```
root@Named:~# curl google.com
<HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8">
<TITLE>301 Moved</TITLE></HEAD><BODY>
<H1>301 Moved</H1>
The document has moved
<A HREF="http://www.google.com/">here</A>.
</BODY></HTML>
root@Named:~# curl ip.sb
153.122.163.*
```

kkr 程序下载时报错如下
```
root@Named:~# kkr --debug -d "https://youtu.be/9HWQ9I18oAM" --live
使用至多 10 线程下载
正在获取视频信息
Error: Request failed with status code 403
获取直播信息失败 稍后重试
```

**Comment by Last-Order** [comment]
proxychains

**Comment by xxxxuanran** [comment]
> proxychains

感谢作者回复。
在我这台 Ubuntu 上，proxychains 与 proxychains-ng 似乎并无法完全代理 kkr。或许是用法错误，烦请指正。
测试如下
```
root@Named:~# proxychains4 curl ip.sb
[proxychains] config file found: /etc/proxychains4.conf
[proxychains] preloading /usr/lib/x86_64-linux-gnu/libproxychains.so.4
[proxychains] DLL init: proxychains-ng 4.14
[proxychains] Strict chain  ...  172.31.64.1:7890  ...  ip.sb:80  ...  OK
210.3.53.*
root@Named:~# proxychains4 curl https://google.com
[proxychains] config file found: /etc/proxychains4.conf
[proxychains] preloading /usr/lib/x86_64-linux-gnu/libproxychains.so.4
[proxychains] DLL init: proxychains-ng 4.14
[proxychains] Strict chain  ...  172.31.64.1:7890  ...  google.com:443  ...  OK
<HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8">
<TITLE>301 Moved</TITLE></HEAD><BODY>
<H1>301 Moved</H1>
The document has moved
<A HREF="https://www.google.com/">here</A>.
</BODY></HTML>
```
kkr 报如下错误
```
root@Named:~# proxychains4 kkr --debug -d https://youtu.be/9HWQ9I18oAM
[proxychains] config file found: /etc/proxychains4.conf
[proxychains] preloading /usr/lib/x86_64-linux-gnu/libproxychains.so.4
[proxychains] DLL init: proxychains-ng 4.14
[proxychains] DLL init: proxychains-ng 4.14
使用至多 10 线程下载
正在获取视频信息
[proxychains] Strict chain  ...  172.31.64.1:7890  ...  youtube.com:443  ...  OK
[proxychains] Strict chain  ...  172.31.64.1:7890  ...  www.youtube.com:443  ...  OK
/root/.nvm/versions/node/v16.1.0/lib/node_modules/kkr/dist/core/downloader.js:70
                throw new DownloadError("无法获得可用的直播地址");
                      ^

DownloadError: 无法获得可用的直播地址
    at Downloader.<anonymous> (/root/.nvm/versions/node/v16.1.0/lib/node_modules/kkr/dist/core/downloader.js:70:23)
    at Generator.next (<anonymous>)
    at fulfilled (/root/.nvm/versions/node/v16.1.0/lib/node_modules/kkr/dist/core/downloader.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by Last-Order** [comment]
@xxxxuanran 该视频已转码，非直播视频，请使用其他工具下载
