### ISSUE TITLE
linux下载完成后无法合并 

### ISSUE THREAD

**Issue by cykac04** [Last-Order/kkr#11]
是Ctrl+c的问题吗?

```
Ctrl+C 被按下 等待当前任务下载完毕
(node:1116944) UnhandledPromiseRejectionWarning: TypeError: seqs.flat is not a function
    at LiveDownloader.<anonymous> (/usr/local/lib/node_modules/kkr/dist/core/live_downloader.js:249:30)
    at Generator.next (<anonymous>)
    at /usr/local/lib/node_modules/kkr/dist/core/live_downloader.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/usr/local/lib/node_modules/kkr/dist/core/live_downloader.js:4:12)
    at LiveDownloader.beforeExit (/usr/local/lib/node_modules/kkr/dist/core/live_downloader.js:182:16)
    at LiveDownloader.<anonymous> (/usr/local/lib/node_modules/kkr/dist/core/live_downloader.js:145:26)
    at Generator.next (<anonymous>)
    at /usr/local/lib/node_modules/kkr/dist/core/live_downloader.js:8:71
    at new Promise (<anonymous>)
(node:1116944) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1116944) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

**Comment by Last-Order** [comment]
node版本不够 升级一下
