### ISSUE TITLE
UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'title' of undefined

### ISSUE THREAD

**Issue by ForsakenRei** [Last-Order/kkr#15]
C:\Users\Username>kkr -d https://www.youtube.com/watch?v=0XxV0fZeMGQ --live
正在获取视频信息
获取视频信息失败
获取视频信息失败 第 1 次重试
获取视频信息失败 第 2 次重试
(node:22588) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'title' of undefined
    at LiveDownloader.<anonymous> (C:\Users\UsernameAppData\Roaming\nvm\v14.18.1\node_modules\kkr\dist\core\live_downloader.js:103:53)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\Username\AppData\Roaming\nvm\v14.18.1\node_modules\kkr\dist\core\live_downloader.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:22588) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
(node:22588) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

kkr 1.2.9
Node 14.18.1
Win10 21H2/Manjaro 21.2
获取视频信息失败之后直接terminate掉了，看起来是没抓到Title？
链接是个没有实时回放的直播，试了一下另一个直播同样的错误，看来是我环境问题？

**Comment by ForsakenRei** [comment]
排查了一番发现用kkr时会触发奇怪的pi-hole规则导致youtube.com被屏蔽，暂时停用pi-hole或者加白名单问题解决，目前没研究清楚问题到底出在哪……
